name: twitter_embed_card
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  vector_graphics: ^1.1.11+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  vector_graphics_compiler: ^1.1.11+1

flutter:
  uses-material-design: false
  assets:
    # Regular assets
    - path: assets/media-query-banner.jpg
    - path: assets/andrea-avatar.png
    # SVGs to be transformed
    - path: assets/icon_comment.svg
      transformers:
        - package: vector_graphics_compiler
    - path: assets/icon_heart_blue.svg
      transformers:
        - package: vector_graphics_compiler
    - path: assets/icon_heart_red.svg
      transformers:
        - package: vector_graphics_compiler
    - path: assets/icon_info.svg
      transformers:
        - package: vector_graphics_compiler
    - path: assets/icon_link.svg
      transformers:
        - package: vector_graphics_compiler
    - path: assets/icon_verified.svg
      transformers:
        - package: vector_graphics_compiler
    - path: assets/icon_x.svg
      transformers:
        - package: vector_graphics_compiler
